languageCode = "en"
languageName = "English"
languageDirection = "ltr"
weight = 1

title = "Techkroken"
# copyright = "Copy, _right?_ :thinking_face:"

[params]
  dateFormat = "2 January 2006"

  mainSections = ["posts"]
  description = "I write to remember. Here's my collection of technical notes"

[params.author]
  name = "Marit Iren R. Tokle"
  image = "img/author.jpg"
  headline = "Senior Software Engineer | Application Security & Developer Experience"
  bio = "I specialize in application security and DevOps practices, focusing on integrating security into development workflows. Here I document solutions to problems I've solvedâ€”mainly for future me, but hopefully useful to you too."
  links = [
    { email = "mailto:marit@tokle.dev" },
  #   { link = "https://link-to-some-website.com/" },
  #   { codepen = "https://codepen.io/username" },
  #   { dev = "https://dev.to/username" },
  #   { discord = "https://discord.gg/invitecode" },
    { github = "https://github.com/maritiren" },
  #   { gitlab = "https://gitlab.com/username" },
  #   { google = "https://www.google.com/" },
  #   { instagram = "https://instagram.com/username" },
  #   { linkedin = "https://linkedin.com/in/username" },
  #   { medium = "https://medium.com/username" },
  #   { mendeley = "https://www.mendeley.com/" },
  #   { microsoft = "https://www.microsoft.com/" },
  #   { stack-overflow = "https://stackoverflow.com/users/userid/username" },
  ]
